language: python
python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5
env:
    - DJANGO_VERSION=1.9.*
    - DJANGO_VERSION=1.8.*
install:
    - pip install Django=="$DJANGO_VERSION"
    - python setup.py install
script:
    - if [[ $DJANGO_VERSION != 1.9.* || $TRAVIS_PYTHON_VERSION != 3.3 ]]; then python setup.py test; fi
